import { useMemo } from 'react'
import {
  Bell,
  Loader2,
  AlertCircle,
  CheckCircle,
  Clock,
} from 'lucide-react'
import { useAlerts, useResolveAlert } from '../hooks/useAlerts'
import { StatusBadge } from '../components/StatusBadge'
import { cn } from '../lib/cn'
import type { Alert } from '../types'

function formatDateTime(value: string): string {
  return new Date(value).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

const THRESHOLD_STYLES: Record<number, string> = {
  90: 'text-status-valid bg-status-valid-bg/10',
  60: 'text-status-expiring bg-status-expiring-bg/10',
  30: 'text-status-expired bg-status-expired-bg/10',
}

export function AlertsPage() {
  const alertsQuery = useAlerts()
  const resolveMutation = useResolveAlert()

  const alerts = useMemo(() => alertsQuery.data ?? [], [alertsQuery.data])

  const sortedAlerts = useMemo(() => {
    const urgency: Record<number, number> = { 30: 3, 60: 2, 90: 1 }
    return [...alerts].sort((a, b) => {
      const urgencyDiff = (urgency[b.alert_threshold_days] ?? 0) - (urgency[a.alert_threshold_days] ?? 0)
      if (urgencyDiff !== 0) return urgencyDiff
      return new Date(b.generated_at).getTime() - new Date(a.generated_at).getTime()
    })
  }, [alerts])

  const handleResolve = (alertId: number) => {
    resolveMutation.mutate(alertId)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-2">
          <Bell className="h-5 w-5 text-navy-300" aria-hidden="true" />
          <h1 className="text-xl font-bold tracking-tight text-navy-50">
            Active Alerts
          </h1>
        </div>
        <p className="text-sm text-navy-400">
          Document expiry alerts generated by threshold monitoring
        </p>
      </div>

      {alertsQuery.isLoading && (
        <div className="flex items-center justify-center rounded-xl border border-navy-800 bg-navy-900 p-12">
          <Loader2 className="h-6 w-6 animate-spin text-navy-300" />
          <span className="ml-3 text-sm text-navy-300">Loading alerts...</span>
        </div>
      )}

      {alertsQuery.isError && (
        <div
          role="alert"
          className="flex items-center gap-3 rounded-xl border border-status-expired/40 bg-status-expired-bg/10 p-6"
        >
          <AlertCircle className="h-5 w-5 shrink-0 text-status-expired" />
          <p className="text-sm text-status-expired">
            Failed to load alerts. Please try again later.
          </p>
        </div>
      )}

      {!alertsQuery.isLoading && !alertsQuery.isError && sortedAlerts.length === 0 && (
        <div className="flex flex-col items-center justify-center rounded-xl border border-navy-800 bg-navy-900 p-12">
          <CheckCircle className="mb-3 h-8 w-8 text-status-valid" />
          <p className="text-sm text-navy-400">No active alerts. All documents are within compliance.</p>
        </div>
      )}

      {!alertsQuery.isLoading && !alertsQuery.isError && sortedAlerts.length > 0 && (
        <div className="overflow-hidden rounded-xl border border-navy-800 bg-navy-900">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-navy-800 bg-navy-800">
                <tr>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Crew Member
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Document Type
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Threshold
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Expiry Date
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Generated
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Status
                  </th>
                  <th scope="col" className="px-4 py-3 font-semibold text-navy-200 whitespace-nowrap">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {sortedAlerts.map((alert: Alert) => (
                  <tr
                    key={alert.alert_id}
                    className="transition-colors hover:bg-navy-800/50"
                  >
                    <td className="px-4 py-3 whitespace-nowrap font-medium text-navy-50">
                      {alert.seafarer_name}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-navy-200">
                      {alert.document_type}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span
                        className={cn(
                          'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium',
                          THRESHOLD_STYLES[alert.alert_threshold_days] ?? 'text-navy-300 bg-navy-800',
                        )}
                      >
                        <Clock className="h-3 w-3" aria-hidden="true" />
                        {alert.alert_threshold_days} days
                      </span>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-navy-200">
                      {new Date(alert.expiry_date).toLocaleDateString('en-GB', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric',
                      })}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-navy-300">
                      {formatDateTime(alert.generated_at)}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <StatusBadge status={alert.document_status} />
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <button
                        type="button"
                        onClick={() => handleResolve(alert.alert_id)}
                        disabled={resolveMutation.isPending}
                        className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium text-status-valid transition-colors hover:bg-status-valid-bg/20 focus:outline-none focus:ring-2 focus:ring-navy-400/40 disabled:opacity-50"
                        aria-label={`Resolve alert for ${alert.seafarer_name} - ${alert.document_type}`}
                      >
                        <CheckCircle className="h-3.5 w-3.5" aria-hidden="true" />
                        Resolve
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {resolveMutation.isError && (
        <div
          role="alert"
          className="flex items-center gap-3 rounded-xl border border-status-expired/40 bg-status-expired-bg/10 p-4"
        >
          <AlertCircle className="h-5 w-5 shrink-0 text-status-expired" />
          <p className="text-sm text-status-expired">
            {resolveMutation.error instanceof Error
              ? resolveMutation.error.message
              : 'Failed to resolve alert.'}
          </p>
        </div>
      )}
    </div>
  )
}
